name: Do something with the matrix value

on:
  push:
    branches:
      - dockerbuildtest

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '6.0.x' ]
        go-version: [ '1.14', '1.15', '1.16.x' ]

    defaults:
      run:
        working-directory: ./src
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: C# Unit Tests
        run: |
          cd cartservice/src

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
     
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
     
      - name: Test
        timeout-minutes: 10
        run: dotnet test --no-restore --verbosity normal

      - name: Go Unit Tests
        run: |
          cd shippingservice

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json
      
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
