name: Do something with the matrix value

on:
  push:
    branches:
      - main
     paths: ['./src*','.github/workflows/dockerbuildd.yml']

jobs:
  build:
    runs-on: ubuntu-latest
     defaults:
      run:
        working-directory: ./src
    
    strategy:
      matrix:
        dir: [productcatalogservice, shippingservice, frontend,checkoutservice]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        working-directory: ${{ matrix.dir }}
        run: go build -v ./..
