name: Do something with the matrix value

on:
  push:
    branches:
      - dockerbuildtest

jobs:
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: C# Unit Tests
        timeout-minutes: 10
        run: |
          dotnet test src/cartservice/

      - name: Go Unit Tests
        timeout-minutes: 10
        run: |
          cd ./src/shippingservice
            echo "Testing $SERVICE..."
            pushd src/$SERVICE
            go test
            popd
          done
